### ISSUE TITLE
August 7 build review

### ISSUE THREAD

**Issue by laurenlangley** [firefox0102/waterwatch#2]
Pete, this site is looking and working great!! Here's a design review - nothing crazy just picky design things :)

Page: Sign In form
- [x] Change 'Site Admin' to 'ADMIN'
- [x] form header text should be white
- [x] button text should be white by default and hover
- [x] 'Sign In' heavier weight 500
- [x] font-color for form text and input baseline border should be #7D7D7D throughout site
- [x] 'Forget Password' move up to start 16px from Password input baseline (unless a hidden error needs that space)
- [x] Top nav 'ADMIN' and lock icon should be green (active) in this view

Header:
- [x] Set of logos to start 40px from left
- [x] Set of nav links to align right 40px from right

Footer:
- [x] 106 height instead of 140 height
- [x] <a> tag should be font-color #7FBA00
- [x] remove period '.' from end of email address
- [x] icon group margin-bottom 6px

Log Data:
- [x] 'Log new data...' font-color #7D7D7D
- [ ] Logbook Number: why dotted input baseline?
- [x] select menu hover background #EDF2F5 and font-color #004D71
- [x] 'See More Parameters' change to 'Hide More Parameters' when expanded

Collection Sites:
- [x] Export select dropdown baseline: can you make that green?
- [x] Date picker header background: use navy blue #004D71 and white text

I'll wait to review Data tab until it's closer to completion

**Comment by firefox0102** [comment]
@laurenlangley Took care of everything except the dotted line one
"Logbook Number: why dotted input baseline?"
It's there because it's a disabled input, I figured it might be intuitive if it stood out.
Should I make it a solid line as well?

You can check out the remediation on "pf/style-remediation-1"

**Comment by firefox0102** [comment]
👍
