### ISSUE TITLE
Left To-Do

### ISSUE THREAD

**Issue by lslangley** [firefox0102/waterwatch#9]
From 08/11 Check-in |   |   | Assigned to | Hours |  Status
-- | -- | -- | -- | -- | --
Add New Parametrs | OK | Air Temp, Water Temp, Secchi Depth | Peter | 0.5 |  Done
Map Pins | OK | Add number of sites - cluster | Leslie | 2 |  Done
UI review: Admin | OK |   | Lauren | 1 |  Done
UI review: Data/Map | OK |   | Lauren | 1 |  Done
Socail Links | Done |   | Peter | 0 |  Done
Required Field List | Yes with Erik | Data validation per field, Range Validation, Required Field List | Leslie | 2 |  Done
ECOL..Formuals | Yes with Erik |   | Leslie | 5 |  Done
Migration | Yes with Erik |   | Leslie / Lauren | 5 |  Done
**CRK Firebase Account | Yes with Erik | Create it prior to migration | Leslie | 0.5 |**  
Data Log default current date | Yes with Erik |   | Peter | 0.5 |  Done
Lab Default | Yes with Erik | Atlanta as default | Peter | 0.5 |  Done
Edit Data from table |   | modal or in line or back to log with update button instead of save with re-route to | Lauren + Peter | 2.5 |  Done
Entering data before log number is created | push back | clarify - just in case with erik | Leslie | 0.1 | Done 
Search | OK |   | Peter | 1 |  Done
Date Picker | Done |   | Peter | 0 |  Done
HUC List | OK | map question | Leslie | 1 |  Done
New collection data UI | OK | Style needed | Lauren | 1 |  Done 
Typeahead in search | OK | add | Peter | 2 |  Done
Table | OK | Drop down - is public? to hide from mapTable structure - Active/ Inactive/Public/Private ...query by data range and data type. Default to last 6 months of data for each table | Peter | 2 |  Done
Chart controls on front page | Done |   | Peter | 0 |  Done
remove map layers from upper right | OK |   | Peter | 0.1 |  Done
add coordinates from field | Push Back |   | Leslie | 0 |  Not in scope
Admin tracking | Push Back |   | Leslie | 0 |  Not in scope
Archive/ Delete | OK | Archive from app / Delete from firebase only | Leslie | 1 |  Done
  |   |   |   |   |  
  |   |   |   |  TOTAL EST. | 27.8
  |   |   |   |   |  
ONGOING SCOPED TO-DO's |   |   |   |   |  
Map/Chart/Search interactivity |   |   | Leslie | 10 |  Done
**Report generators |   |   | Leslie | 15 |**  
Test + Deploy |   |   | Leslie | 5 |  Done
Integrating real data into chart |   |   | Peter | 1.5 |  Done
Integrating real data into map |   |   | Leslie | 5 |  Done
**User guide write up |   |   | Lauren | 4 |**  
  |   |   |   |   |  
  |   |   |   | TOTAL EST.  | 40.5

**Comment by lslangley** [comment]
# Erik Meeting - 08/22/2017 
## **Pre-populated  fields but all editable**
- Today's  date 
- Rainfall @ 0.00 (may need to be text so Trace or T can be entered but would need to be converted to 0 for graphs)
- incubation temp
- Analyst (with previous entry)
- Lab (Atlanta)

## **Required Fields** 
- Station name - search and typeahead
- Date
- new site form - toggle "permanent" (mapped) or "temporary site" (not mapped) not mapped needs not coordinate validation 

## **Submit Confirmation Card**
- add  what fields are missing (not including additional parameters)

## **Ranges**
- Incubation time- within 6 hours of collections
- dilution must be a whole number
- fluorometry - 0 - 200 no flag > 200 "are you sure" alert with the ability to confirm
- turbidity - 0 - 1000 "are you sure" alert with the ability to confirm
- conductivity 0 - 750 "are you sure" alert with the ability to confirm
- "<#" treats as text instead of integer 
- incubation temp = 10 and 50 "are you sure" alert with the ability to confirm
- incubation out - between 18 and 22 hrs of incubation in 
- Coliform large cell - 0 - 49 whole number
- Coliform small cell - 0 -48 whole number
- E.coli large cell - 0 - 49 whole number
- E.coli small cell - 0 -48 whole number

## **Additional Parameter**
 Add units to be sent by Erik

## **Calculations** 
- quanti table coefficient (same for coliform + E.coli) * 100/ dilution 

## **Unique identifier**
- suggest interns to enter by alphabetical order
- for report - sort by date then site name alphabetically

## **Editing a previous collection site**
- ensure ability to add e.coli/coliform large and small cells- like editing form

## **HUCS**
- med res zoom out
- high res zoomed in 
- http://www.arcgis.com/home/item.html?id=c3cbe1eaf6f4492db74e62f7f4ba2418
- HUC name in pop up
- huc reference when coordinates edited

## **map**
- api for erik's esri map?

**Comment by lslangley** [comment]
@firefox0102 
A gift of units for the form:
DO – mg/L
Nitrate – mg/L
Phosphate – mg/L
Ammonium – mg/L
Total Chlorine – mg/L
Secchi Depth – meters
Chlorophyll-a - µg/L
Water Temp – deg C
Air Temp – deg C

**Comment by firefox0102** [comment]
Done:
- [x] Log Data: Add new parameters to form (Air water temp, secchi depth)
- [x] Log Data: Add metrics to form labels
- [x] Log Data: Default current date
- [x] Log Data: Default Atlanta as lab
- [x] Log Data: Save “Last E. coli result” and other metrics on collection site when saving
- [x] Log Data: Add units to missing log data fields
- [x] Reports Page: Default to last 6 months of data
- [x]  Collection Sites: Default to last 6 months of data
- [x] Collection Sites: Edit data from the table
- [x] Collection Sites: Archiving and unarchiving
- [x]  Graph Page: Get Graphs displaying data for specific collection site
- [x] Graph Page: Chart controls on front page 
- [x] Graph Page: remove map layers from upper right
- [x]  Graph Page: Get Data page sidebar filtering working
- [x]  Graph Page: Create floating info box for Map


To Do:
- [x] Log Data: Autocomplete for collection sites (disable this when editing, can't change collection site)
- [x] Log Data: Set the min and max ranges for correct fields
- [x] Log Data: Ensure that pre populated fields are in place
- [x] Log Data: Save “total E. coli result” and other metrics on report when saving, and display them instead of computed properties
- [x] Log Data: Fix equation for E. coli (update graph page and what you're saving on log data page)
- [x] Log Data: Fix equation for Coliform
- [x] Log Data: Increment number of samples collected metric on collection site object
- [x] *Ask Leslie if we need to save these things as strings so we can include the units
- [x] Reports Page: Edit data from the table
- [x] Collection Sites: When archiving, increment or decrement num active sites accordingly
- [x] Look for TODOs in app and verify

Questions:
- Get lauren to look over archiving and unarchiving (we can't use table menus, but also table menus are annoying with these huge tables)
- Do they want us to automatically save the last E. coli and coliform data when saving a form? Or do they want to enter it manually each time?
- What's the difference between "Trace" rainfall and 0? Can we not just enter 0?
- Need copy for Rainfall, Turbidity, and Conductivity charts

**Comment by firefox0102** [comment]
Fix collection site editing fields

**Comment by firefox0102** [comment]
- [ ] Use the other type of datepicker and modify modal class to be wider

**Comment by laurenlangley** [comment]
## Notes from Meeting 9/17/17

**Pete To Do:**
- [x] Date pickers - use picker dropdown instead of opening a modal
- [x] For editing site data, open a modal instead of redirecting to Log Data page
- [x] Add public and private feature for collection site list - private will not display site on map
- [x] Log Data form - Logbook Number input line is dotted because it's disabled. Fix so not disabled/dotted
- [x] Log Data form - Rainfall link to weather underground url: https://www.wunderground.com/history/
- [x] Log Data form - Field validation inline errors (e.g. if value is out of range or wrong value type)

**Notes:**
- [x] Lauren to design review Admin site
- [x] Lauren to populate Firebase with historical data from one actual collection site
- [ ] Lauren to style Add New Site modal
- [ ] Lauren to get copy for chart 'more information' blurbs
- [x] Lauren and Leslie to work on data migration plan
- [ ] Leslie to work on map layers and report export functionality for consumer-facing page
- [x] Lauren to style / design review map/data page when close to finished

**Questions/Comments for Erik:**
- [x] Rainfall - trace levels will equal 0.00
- [x] Cannot mix string and num values in data structure
- [x] Need full list of HUCS and Partners they want to use
- [x] For data migration, need full logbook data exports (spreadsheets from NWW site only have total collectionDate, totalEcoli, precipitation, specificConductivity)
- [x] Make sure google maps urls include the fully qualified path (EX. don't forget https://)
- [x] Header: Do you want the logos to link elsewhere or not? CRK > CRK, NWW > NWW?
- [ ] About page: Content taken from CRK site - ok?; ’Are the fish safe…” referenced link is broken. Have a fix?
- [x] Log Data: more parameters - order okay?
- [x] Collection Site Data page - how many of the parameters do they want to see in the table vs on export and what order?

**Comment by firefox0102** [comment]
- [x] Incubation time- within 6 hours of collections
- [x] incubation out - between 18 and 22 hrs of incubation in
- [x] dilution must be a whole number
- [x] Coliform large cell - 0 - 49 whole number
- [x] Coliform small cell - 0 -48 whole number
- [x] E.coli large cell - 0 - 49 whole number
- [x] E.coli small cell - 0 -48 whole number
- [x] fluorometry - 0 - 200 no flag > 200 "are you sure" alert with the ability to confirm
- [x] turbidity - 0 - 1000 "are you sure" alert with the ability to confirm
- [x] conductivity 0 - 750 "are you sure" alert with the ability to confirm
- [x] incubation temp = 10 and 50 "are you sure" alert with the ability to confirm
